name: Android SDK CD

on:
  workflow_dispatch:

jobs:
  release:
    name: Build & Release SDK
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build SDK
        run: ./gradlew assembleRelease

      - name: Create Release Tag
        id: version
        run: |
          VERSION_NAME=$(./gradlew -q printVersion)
          git tag v$VERSION_NAME
          git push origin v$VERSION_NAME
          echo "version=$VERSION_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.version }}
          name: "SDK Release v${{ env.version }}"
          draft: false
          prerelease: false
          body: "New SDK Release v${{ env.version }}"
          files: sdk/build/outputs/aar/*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}