name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ master ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add permissions restriction
permissions:
  contents: read

jobs:
  build:
    # Only run this workflow for authorized contributors
    if: |
      (github.event_name == 'push' && github.repository_owner == 'Imprint-Tech') ||
      (github.event_name == 'pull_request' && 
        (github.event.pull_request.user.login == github.repository_owner || 
         endsWith(github.event.pull_request.user.email, '@imprint.co')))

    runs-on: self-hosted

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      # Set timeout to prevent long-running jobs from hogging resources
      - name: Checkout SDK Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Limit git history to reduce exposure
          persist-credentials: false  # Don't persist GitHub credentials

      # Setup Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Grant execute permission for gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build SDK
      - name: Build SDK
        run: |
          set -o pipefail
          ./gradlew :sdk:clean :sdk:assembleRelease | grep -v "sensitive"

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          set -o pipefail
          ./gradlew :sdk:testReleaseUnitTest | grep -v "sensitive"

      # Run Android Lint
      - name: Run Android Lint
        run: |
          set -o pipefail
          ./gradlew :sdk:lintRelease | grep -v "sensitive"

      # Test JitPack/Maven integration
      - name: Validate Maven Publication
        run: |
          set -o pipefail
          ./gradlew :sdk:publishToMavenLocal | grep -v "sensitive"

      # Test Demo App Integration
      - name: Build Demo App
        run: |
          set -o pipefail
          ./gradlew :sdk-demo:clean :sdk-demo:assembleDebug | grep -v "sensitive"

      # Clean up workspace
      - name: Clean up
        if: always()
        run: |
          set -x
          rm -rf ~/.gradle/caches/
          rm -rf build/
          rm -rf */build/